POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "fatimabobo@gmail.com",
  "password": "secret",
  "firstname": "fatima",
  "minit": "B",
  "lastname": "Trawalleh"
}


###
POST http://localhost:3001/api/sale HTTP/1.1
content-type: application/json 

{
  "description": "beans",
  "qty": 5,
  "price": 70,
  "total": 350,
  "userId": "636f744db1eacc13bff0ff84"
  
}
