POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "oumon1@gmail.com",
  "password": "secret",
  "firstname": "oumon",
  "minit": "B",
  "lastname": "bah"
}


###
POST http://localhost:3001/api/sale HTTP/1.1
content-type: application/json 

{
  "description": "mbahal",
  "qty": 4,
  "price": 100,
  "total": 400,
  "userId": "636f744db1eacc13bff0ff84"
  
}
