DELETE http://localhost:3001/api/sale/6378d41badc09f5b2ed57872

###sale
DELETE http://localhost:3001/api/sale/6378d41badc09f5b2ed57872
content-type: application/json

{
"userId": "636b76ea9daaabbcecf21442"
}