PUT http://localhost:3001/api/user/6377db1c9d437c0167c26a0d
 content-type: application/json
 
 {
  "description": "benachin",
  "qty": 2,
  "price": 20,
  "total": 40,
  "userId": "636f744db1eacc13bff0ff84"
  
}